require 'json'
require 'httparty'

all_champions = [
  'Aatrox',
  'Ahri',
  'Akali',
  'Akshan',
  'Alistar',
  'Amumu',
  'Anivia',
  'Annie',
  'Aphelios',
  'Ashe',
  'AurelionSol',
  'Azir',
  'Bard',
  'Belveth',
  'Blitzcrank',
  'Brand',
  'Braum',
  'Caitlyn',
  'Camille',
  'Cassiopeia',
  'Chogath',
  'Corki',
  'Darius',
  'Diana',
  'Draven',
  'DrMundo',
  'Ekko',
  'Elise',
  'Evelynn',
  'Ezreal',
  'Fiddlesticks',
  'Fiora',
  'Fizz',
  'Galio',
  'Gangplank',
  'Garen',
  'Gnar',
  'Gragas',
  'Graves',
  'Gwen',
  'Hecarim',
  'Heimerdinger',
  'Illaoi',
  'Irelia',
  'Ivern',
  'Janna',
  'JarvanIV',
  'Jax',
  'Jayce',
  'Jhin',
  'Jinx',
  'Kaisa',
  'Kalista',
  'Karma',
  'Karthus',
  'Kassadin',
  'Katarina',
  'Kayle',
  'Kayn',
  'Kennen',
  'Khazix',
  'Kindred',
  'Kled',
  'KogMaw',
  'KSante',
  'Leblanc',
  'LeeSin',
  'Leona',
  'Lillia',
  'Lissandra',
  'Lucian',
  'Lulu',
  'Lux',
  'Malphite',
  'Malzahar',
  'Maokai',
  'MasterYi',
  'MissFortune',
  'MonkeyKing',
  'Mordekaiser',
  'Morgana',
  'Nami',
  'Nasus',
  'Nautilus',
  'Neeko',
  'Nidalee',
  'Nilah',
  'Nocturne',
  'Nunu',
  'Olaf',
  'Orianna',
  'Ornn',
  'Pantheon',
  'Poppy',
  'Pyke',
  'Qiyana',
  'Quinn',
  'Rakan',
  'Rammus',
  'RekSai',
  'Rell',
  'Renata',
  'Renekton',
  'Rengar',
  'Riven',
  'Rumble',
  'Ryze',
  'Samira',
  'Sejuani',
  'Senna',
  'Seraphine',
  'Sett',
  'Shaco',
  'Shen',
  'Shyvana',
  'Singed',
  'Sion',
  'Sivir',
  'Skarner',
  'Sona',
  'Soraka',
  'Swain',
  'Sylas',
  'Syndra',
  'TahmKench',
  'Taliyah',
  'Talon',
  'Taric',
  'Teemo',
  'Thresh',
  'Tristana',
  'Trundle',
  'Tryndamere',
  'TwistedFate',
  'Twitch',
  'Udyr',
  'Urgot',
  'Varus',
  'Vayne',
  'Veigar',
  'Velkoz',
  'Vex',
  'Vi',
  'Viego',
  'Viktor',
  'Vladimir',
  'Volibear',
  'Warwick',
  'Xayah',
  'Xerath',
  'XinZhao',
  'Yasuo',
  'Yone',
  'Yorick',
  'Yuumi',
  'Zac',
  'Zed',
  'Zeri',
  'Ziggs',
  'Zilean',
  'Zoe',
  'Zyra'
]

namespace :riot_api do
  task fetch_champions: :environment do
    puts 'Seeding champion data...'

    all_champions.each do |champion|
      puts "Getting data for #{champion}..."
      response = HTTParty.get "http://ddragon.leagueoflegends.com/cdn/12.21.1/data/en_US/champion/#{champion}.json"
      data = response['data'][champion]
      champ = Champion.create(
        {
          name: data['name'],
          key: data['key'],
          title: data['title'],
          image_full: data['image']['full'],
          image_sprite: data['image']['sprite'],
          lore: data['lore'],
          blurb: data['blurb'],
          hp: data['stats']['hp'].to_i,
          move_speed: data['stats']['movespeed'].to_i,
          armor: data['stats']['armor'].to_i,
          attack_range: data['stats']['attackrange'].to_i,
          attack_damage: data['stats']['attackdamage'].to_i,
          crit: data['stats']['crit'].to_f,
          attack: data['info']['attack'].to_i,
          defense: data['info']['defense'].to_i,
          magic: data['info']['magic'].to_i,
          difficulty: data['info']['difficulty'].to_i,
          primary_role: data['tags'][0].downcase,
          secondary_role: data['tags'][1].downcase,
          enemy_tips: data['enemytips'].join(' '),
          ally_tips: data['allytips'].join(' ')
        }
      )
      %w[pt_BR es_ES].each do |locale|
        response = HTTParty.get "http://ddragon.leagueoflegends.com/cdn/12.21.1/data/#{locale}/champion/#{champion}.json"
        data = response['data'][champion]

        i18n_locale = locale == 'pt_BR' ? :'pt-BR' : :es
        I18n.with_locale(i18n_locale) do
          champ.title = data['title']
          champ.lore = data['lore']
          champ.blurb = data['blurb']
          champ.enemy_tips = data['enemytips'].join(' ')
          champ.ally_tips = data['allytips'].join(' ')
        end
      end
      puts "Failed to load seed data for champion #{champion}!" unless champ.save
    end
  end
end
