AllCops:
  NewCops: enable
  Exclude:
    - './bin/bundle'
    - './bin/importmap'
    - './bin/rails'
    - './bin/rake'
    - './bin/setup'
    - './config/puma.rb'
    - './config.ru'
    - './vendor/**/*'

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false